//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;

public class Answer
{
	public String name;
	public bool correct;
}
public class Question
{
	public String name;
	public ArrayList answers;
	public Question (String name)
	{
		this.name = name;
		this.answers = new ArrayList ();
	}
	public Question AddAnswer(String name, bool correct)
	{
		Answer answer = new Answer ();
		answer.name = name;
		answer.correct = correct;
		answers.Add (answer);
		return this;
	}
}
